### ISSUE TITLE
For Beta

### ISSUE THREAD

**Issue by Yorvoration** [mxbek/GammaPrint#2]
maylimi ozgina qo`shimcha kiritsam

**Comment by mxbek** [comment]
Iy end qana qoshimcha kiritasakan...?

**Comment by Yorvoration** [comment]
ozgina sintaxsis xatolari bor edi hato deb bo`lmaydi lekin kamchilik baribir adashmasam

**Comment by mxbek** [comment]
Nu ok rahmat bu huddi tashlab ketilgan qizdek edi bu project toris
